spring:
  profiles:
    active: test

server:
  port: 9090
  tomcat:
    accept-count: 200
    max-threads: 1000
    connection-timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

